# Generated by Django 5.0.7 on 2024-09-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_product_name_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
